prgrms-fe-devcourse/FEDC5_dopen_Hoil

.gitignore
src/apis/instance.ts
src/apis/type.ts
tsconfig.json

문서를 토대로 API resonse data 타입을 지정했고, axios create를 통해 instance를 생성하였습니다
#9 
[vite 환경변수 관련 문서](https://ko.vitejs.dev/guide/env-and-mode.html)

[Feature] API resonse data 타입 지정 및 instance 생성

---

src/apis/authentication.ts
src/apis/instance.ts

get,post 요청에 대한 추상화 작업과 인증 관련 API 요청 함수를 추가했습니다
#9 
- 타입스크립트 사용을 잘 한건지 모르겠습니다..  혹시 잘 아시는 분 계신다면 피드백 부탁드립니다
- 문서에 나와있는 주제별로 파일을 나누어서 작업하는 걸 기본으로 하되(인증,사용자..), 제 생각에 관련없는 요청일 경우 좀 빼서 작업할 생각입니다

[Feature] API 추상화 및 인증 관련 함수 추가

---

src/components/Footer/index.tsx
src/components/MainHeader/index.tsx
src/components/PageHeader/index.tsx
src/constants/style.ts
src/stories/components/PageHeader.stories.ts

[Wip] 공통 컴포넌트(3) PageHeader(컨플릭트 해결)

---

src/apis/admin.ts
src/apis/authentication.ts
src/apis/channel.ts
src/apis/comment.ts
src/apis/follow.ts
src/apis/instance.ts
src/apis/message.ts
src/apis/notifications.ts
src/apis/post.ts
src/apis/search.ts
src/apis/type.ts
src/apis/userInfo.ts

- API 요청 함수들을 추가하였습니다
#9
- 문서에 나와있는 분류대로 파일을 나누었습니다.
-  테스트는 한번씩 완료했는데, 혹시 사용하면서 오류가 나거나 불편한 경우 바로 수정하겠습니다
- 함수명이 적절한지 궁금합니다
- 함수에 사용되는 타입들은 최대한 함수와 가까이 위치시켰는데, 좀 지저분하진 않은지 궁금합니다
- 관련된 기능들을 하나의 객체로 만들어서, 각 함수를 메서드처럼 사용하는 건 어떤지 궁금합니다
```
editPost() -> post.edit()
deletePost() -> post.delete()
```

[Feature] API 요청 함수 추가

---

src/pages/MainPage/BoardListPreview.tsx
src/pages/MainPage/Dday.tsx
src/pages/MainPage/GuestProfile.tsx
src/pages/MainPage/LoginProfile.tsx

컴포넌트의 너비를 `width='100%'` => `maxW={DEFAULT_WIDTH} `로 변경하였습니다.
#6 
변경된 것은 너비 값 뿐이기 때문에 보실 내용은 거의 없습니다 !

[Style] MainPage의 컴포넌트 너비 변경

---

src/pages/MainPage/BoardListPreview.tsx

BoardListPreview의 padding 값을 수정했습니다.
- padding -> gap
#6 
padding을 gap으로 바꾼 코드밖에 없어서 봐주실 코드의 양은 작습니다 !

[Style] MainPage BoardListPreview의 padding 값 수정

---

src/components/PageHeader/index.tsx
src/stories/components/PageHeader.stories.ts

- 제목 그대로입니다
#49 
x
간단한 변경사항입니다

[Fix] PageHeader컴포넌트 width, height 프롭스 삭제 및 ...props로 스타일 받게 변경

---

src/components/common/TextIconButton/index.tsx

- TextIconButton에서 다양한 props로 받던 텍스트 스타일을 ...props로 받아와서 최상단 컨테이너에 적용시키는 작업을 하였습니다
#51 
간단한 수정사항입니다~!

[Fix] TextIconButton 컴포넌트 내부 텍스트 스타일을 props로 받아와서 최상단 컨테이너에서 적용하게 수정(간단)

---

src/components/PageHeader/index.tsx

PageHeader height 값을 `DEFAULT_WIDTH` => `DEFAULT_HEADER_HEIGHT` 로 수정했습니다.
값 하나만 수정했습니다 !

[Style] PageHeader height 값 수정

---

src/app/App.tsx
src/pages/Login/index.tsx

- Login 페이지 Logo 이미지 변경
- PageLayout 추가에 따른 내부 Style 수정
- 불필요한 코드 개선
#20 
Style 위주의 수정이다 보니 확인할 부분은 크게 없을 것 같습니다 !
- 추가로 로그인 성공 시 이전 페이지가 회원가입이거나 첫 페이지가 로그인인 경우 Main('/') 페이지로 이동시키고 그게 아니라면 이전 페이지로 이동시키는 로직을 추가했습니다.

[Style] Login(로그인) 페이지 Logo 이미지 변경 및 PageLayout에 따른 style 수정

---

src/utils/isValueUniqueInArray.ts

- isValueUniqueInArray 수정
#2 
부정문 잘못 쓴 코드 수정했습니다 !

[Hotfix] isValueUniqueInArray 수정

---

src/apis/onlineUser.ts
src/app/App.tsx
src/components/OnlineUserProfil/index.tsx
src/components/OnlineUserProfile/index.tsx
src/constants/Board.ts
src/constants/queryKeys.ts
src/hooks/useOnlineUserList.ts
src/pages/BoardEnterPage/index.tsx
src/pages/BoardPage/BoardPostList.tsx
src/pages/BoardPage/OnlineUsers.tsx
src/pages/BoardPage/WriteButton.tsx
src/pages/BoardPage/index.tsx
src/stories/components/OnlineUserProfil.stories.ts
src/stories/pages/BoardPage/BoardPage.stories.tsx

- 특정 게시판 페이지를 구현했습니다.
- 게시판 진입 페이지에서 각 게시판 클릭 시 이동할 수 있도록 처리했습니다.
#44 
- 로직 상 부족한 점은 없는지
- 파일 명, 함수 명, 변수 명은 적절한지
피드백 부탁드립니다 !
useQuery를 처음 사용 해봤는데 잘 사용 했는지 궁금합니다 !

[Feature] 특정 게시판 페이지 구현

---

src/app/App.tsx
src/constants/queryKeys.ts
src/hooks/usePost.ts
src/pages/MyPage/MyBoardList/index.tsx

- 내가 쓴 게시글 페이지 UI 구현
- 내가 작성한 게시글만 나타나도록 구현
- 게시글을 클릭하면 해당 게시글로 이동되도록 구현
#58 
- 작성한 글을 클릭하면 해당 글의 id로 이동하도록 구현했습니다. `/myboardlist/:id`
- useMyPostList(내가 작성한 글 불러오는 hook), usePostDetail(현재 params 값에 해당하는 글이 보이는 hook)

[Feature] MyBoardList(내가 작성한 글 보기) 페이지 UI/기능 구현

---

src/components/common/MyModal/index.tsx
src/pages/MainPage/DdayModal/index.tsx
src/pages/MainPage/LoginDday.tsx
src/utils/calculateDday.ts

- Dday컴포넌트를 제작하였습니다
#76 입니다
- 로컬스토리지 이용하였습니다
- 위 사항 때문에 useEffect 사용 및 setState함수 props전달 이슈가 있습니다 => 좋은방법 있다면 알려주세요
- calculateDday함수 만들어서 dDay구하여 사용했습니다

[Feature] Dday컴포넌트 제작

---

src/hooks/useAdvice.ts
src/pages/MainPage/Dday.tsx
src/pages/MainPage/GuestProfile.tsx
src/pages/MainPage/LoginProfile.tsx
src/pages/MainPage/index.tsx

- 비로그인일 때, 로그인 화면으로 넘어가게 처리
- 로그인 되었을 때 본인의 정보를 가져와 profile에 데이터 처리
- 랜덤 명언 생성 API 도입
#85 
로그인 / 비로그인일 때 동작이 잘 작동하는지, 빼먹은 엣지 케이스는 없는지 확인 부탁 드립니다 !
랜덤 명언 생성 API는 일단 `LoginProfile` 에 두었는데, 이를 hook로 빼는게 바람직하겠죠 ? 팀원분들의 의견을 듣고싶습니다 !

[Feature] MainPage 추가 작업

---

src/app/App.tsx
src/components/PostList/index.tsx
src/components/UserList/index.tsx
src/constants/Board.ts
src/constants/queryKeys.ts
src/hooks/useChannelList.ts
src/hooks/useOnlineUserList.ts
src/pages/BoardEnterPage/index.tsx
src/pages/BoardPage/BoardPostList.tsx
src/pages/BoardPage/WriteButton.tsx
src/pages/BoardPage/index.tsx
src/pages/PostEditPage/index.tsx
src/pages/SearchPage/OptionSelector.tsx
src/pages/SearchPage/index.tsx

- 게시판 목록을 DB에 등록하였고, 이에 따라 router, 게시판 진입 페이지, 특정 게시판 페이지에서의 수정사항이 생겨 작업을 진행했습니다.
#43 #44 
- router 작업을 위해 `App.tsx` 에서 `const { channelListData } = useChannelList();` 코드를 추가하였습니다. `App.tsx`에 데이터 관련 코드가 추가된 것에 대해 어떻게 생각하시나요...? 
App.tsx에는 router 관련 코드만 작성하는게 좋아보이나 channelList 데이터를 가져오는데 오류가 있어서 불가피하게 추가하였습니다. 이에 대해 팀원분들의 의견을 여쭙고 싶습니다 !! 해결 방법에는 어떤 것이 있을까요 ?
- 더 진행되어야 하는 추가 작업이 있을까요? 제가 놓친 부분이 있다면 말씀 부탁드리겠습니다 !
- selectOption 부분이 안되어 있는 것 같아 진행 중입니다 !! 마무리 되는대로 commit 올리겠습니다 !
원래는 post 작성 페이지를 제작하기 위해 `feature/post` 라는 브랜치를 팠으나, post 등록 시 게시판의 ID가 필요하여 부가 작업이 진행되었고 PR이 길어질 것 같아 쪼개서 올립니다 !!

[Fix] DB에 게시판 목록 등록, API를 통해 게시판 목록을 가져온 후 임시 값들 변경

---

src/apis/notifications.ts
src/app/App.tsx
src/constants/queryKeys.ts
src/hooks/useNotificationList.ts
src/pages/MessagePage/Message.tsx
src/pages/NotificationPage/NotificationList.tsx
src/pages/NotificationPage/index.tsx

- 알림 페이지를 작업했습니다
- 알림을 불러오는 API를 통해 알림 리스트를 불러오고, 정규화 과정을 거쳐 해당 리스트를 어떠한 타입인지(메시지,댓글,좋아요,팔로우) , 보낸 유저, 날짜 등으로 바꾼 다음 렌더링하였습니다
- message를 보낼 경우 알림도 같이 보내는 기능을 추가했습니다
#65
- 아직 API에 대한 테스트가 많이 되지는 않은 상태입니다. 나중에 댓글,좋아요 기능이 개발되면 같이 테스트해보면 좋을 것 같습니다.

[Feature] 알림 페이지 작업

---

src/app/App.tsx
src/pages/NotificationPage/NotificationList.tsx
src/test/calculateTimeDiff.test.ts

알림페이지 데이터 없을 시 렌더링할 컴포넌트와 버그를 수정하였습니다

[Fix] 알림페이지 및 간단한 버그 수정

---

src/components/OnlineUserProfile/index.tsx
src/pages/BoardPage/OnlineUsers.tsx

- `OnlineUsers`에서 username 길이가 길어질 시 ... 처리
- 실시간 접속자 간 간격 10px -> 15px 변경
코드 내용은 얼마 없습니다 !

[Fix] OnlineUsers Text 길이가 길어질 시 ... 처리

---

src/assets/send.svg
src/components/Comment/CommentForm.tsx
src/components/Comment/CommentText.tsx
src/components/Comment/index.tsx
src/hooks/useComment.ts
src/hooks/useMyComment.ts
src/hooks/usePost.ts
src/pages/MyPage/MyCommentList/MyCommentListItem.tsx
src/stories/components/Comment.stories.tsx

- Post 게시글에 들어갔을 대 해당 게시글에 저장된 댓글을 보여줍니다.
- 댓글을 삭제할 수 있습니다.(내가 작성한 댓글만 가능합니다.)
- 댓글을 작성할 수 있습니다.
#87 
- 댓글의 경우 어떤 에러 처리를 진행하면 될까요??
- UI를 확인하시려면 App 페이지에 임의로 `path="/comment/:postid" 작성해 주시고 해당 포스트에 맞게 접속하시면 확인 가능합니다.
- 스토리북도 작성하긴 했는데, params를 가지고 와서 api를 호출하다 보니 글목록 부분은 안 보이는 것 같습니다.

[Feature] Comment 댓글 (UI/기능)

---

src/components/OnlineUserProfile/index.tsx

OnlineUserProfile에서 유저 image와 username을 가운데 정렬 했습니다

[Fix] OnlineUserProfile username 가운데 정렬 (1줄 수정)

---

src/components/Footer/index.tsx
src/stories/components/Footer.stories.ts

- Footer컴포넌트에서 랭킹 제거했습니다
#105 
많이 짧습니다

[Fix] Footer컴포넌트에서 랭킹제거 (간단)

---

src/components/PageHeader/index.tsx

아이콘 두개 material design아이콘으로 변경하였습니다
x
매우 간단합니다

[Style] 페이지 헤더 아이콘 변경 (매우간단)

---

src/apis/post.ts
src/pages/MainPage/BoardListPreviewItem.tsx
src/pages/MainPage/GuestProfile.tsx
src/pages/MainPage/LoginProfile.tsx
src/pages/PostEditPage/index.tsx

[Feature] PostEditPage 글 수정 기능 추가

---

src/pages/MyPage/MyBoardList/index.tsx
src/pages/MyPage/MyCommentList/MyCommentListItem.tsx
src/pages/MyPage/MyCommentList/index.tsx

- 내가 작성한 게시글에 작성 시간을 보여준다.
- 내가 작성한 게시글에 타이머 게시판 글을 제외한 게시판의 글을 보여준다.
- 내가 작성한 게시글이 없을 때 알림 문구를 보여준다.
- 내가 작성한 댓글에 작성 시간을 보여준다.
- 내가 작성한 댓글이 없을 때 알림 문구를 보여준다.
#124 
작성한 게시글, 댓글이 없을 때 예외 처리와 게시글에 타이머 게시글은 제외되어 보이도록 수정했습니다.

[Fix] 내가 작성한 게시글, 댓글 페이지 수정

---

src/app/App.tsx
src/components/PageLayout/index.tsx
src/components/common/PrivateRoute/index.tsx
src/hooks/useAuth.ts
src/main.tsx
src/pages/PostViewPage/ErrorFallback.tsx

- PrivateRoute를 이용하여 인증이 필요한 라우트 접근시 인증로직 사용하게 만들었습니다
- 인증되지 않았다면 login페이지로 이동합니다
#127  입니다

[Feature] private route 제작

---

src/components/Grass/index.tsx
src/stories/components/Grass/index.stories.tsx

- 잔디 컴포넌트 상단에 현재 년, 월 표기 + 아이콘 추가하고 가운데 정렬하였습니다
매우간단

[Feature] 잔디컴포넌트 상단에 년,월 추가 및 가운데정렬 (매우간단)

---

src/constants/queryKeys.ts
src/hooks/useStudy.ts
src/pages/UserInfo/UserFollowInfo.tsx
src/pages/UserInfo/UserGrass.tsx
src/pages/UserInfo/UserInfoContainer.tsx
src/pages/UserInfo/index.tsx

- `UserFollowInfo` 컴포넌트에 지금까지 공부한 유저의 누적 기간을 출력했습니다.
- `UserGrass` 컴포넌트에 유저의 공부한 날짜를 시간에 따라 보이도록 했습니다.
- 위 두 컴포넌트를 작업하기 위한 useStudy hook(내가 공부한 시간을 기록하는 채널)을 만들어서 사용했습니다.
#130 
- `Grass` 컴포넌트 사용 시 전달한 데이터가 적절한지 확인해 주시면 감사하겠습니다.
-  추후에 상태 메시지도 보이고 변경 가능하도록 설정해 주고 싶은데, 어떤 필드를 사용하면 좋을까요 ??!
- 유저의 타이머를 기록하는 채널을 확인할 수 있는 `useStudy hook`을 생성했는데 적절한지 궁금합니다.

[Feature] 회원정보 상세보기 페이지(기능 추가)

---

src/pages/MainPage/GrassBox.tsx
src/pages/MainPage/index.tsx

- MainPage에 Grass 컴포넌트를 추가하였습니다.

[Feature] MainPage Grass 컴포넌트 추가 (간단)

---

src/components/common/UserContentBlock/index.tsx
src/pages/PostViewPage/PostDetail/index.tsx
src/pages/ReflectionViewPage/ReflectionDetail/index.tsx

- UserContentBlock에 Image클릭시 온클릭 이벤트 사용할수 있게 프롭스 추가하였습니다 `onImageClick`
- PostDetail, ReflectionPostDetail내부 UserContentBlock에 onClick이벤트에 유저페이지 이동 핸들러 부착하였습니다
#139 
짧습니다

[Fix] UserContentBlock + PostDetail + ReflectionPostDetail (간단)

---

src/components/Comment/CommentForm.tsx
src/components/Comment/CommentText.tsx
src/components/Comment/index.tsx
src/hooks/useComment.ts

- Comment 내부에서 Style 작업했습니다.
- Fixed의 경우 Chakra-ui의 Confirm 컴포넌트 속성에 영향을 받는 것 같아서 Stikcy로 처리했습니다.
- Comment 내부에서 padding으로 간격 줬습니다.
- Comment 작성 완료 후 reset 함수로 value 값을 비워줬습니다.
- Comment 작성은 1글자 ~ 100글자 이하로 처리되도록 예외 처리했습니다.
- Comment 작성 시 작성된 댓글 위치로 이동하도록 처리했습니다.
#142 
- Position을 Fixed로 주면 앱 하단에 동일하게 붙어 있다는 장점이 있고, Stikcy를 사용하면 댓글이 존재하지 않을 때는 댓글 위치에 존재할 수 있습니다. (어떻게 처리하는 게 좋을까요?? 일단 Sticky로 처리했습니다.)

[Fix] Comment 컴포넌트 Stlye 수정 및 입력 예외 처리 작업

---

src/pages/Login/LoginDivider.tsx
src/pages/Login/LoginFindCredentials.tsx
src/pages/Login/LoginForm.tsx
src/pages/Login/LoginLogoTitle.tsx
src/pages/Login/LoginWithSocial.tsx
src/pages/Login/index.tsx
src/pages/Login/loginInputList.ts

- 로그인 페이지를 컴포넌트 단위로 분리했습니다. (페이지 단위가 너무 큰 것 같아서 분리해 봤습니다. 추후에 더 추상화하여 리팩토링하려고 합니다.)
#145

[Fix] Login(로그인) 페이지 분리 작업

---

src/hooks/useStudy.ts

- 아까 급하게 수정하신 `useStudy` hook의 return 문이 빠진 것 같아 제가 빠르게 수정했습니다.
#148 
- return 문만 추가한 코드라서 approve만 눌러주시면 될 것 같습니다 ㅎㅎ

[Hotfix] UseStudy hook (return문 빠진 거 급하게 수정)

---

src/pages/MyPage/Account/index.tsx

- 회원정보 수정 페이지에 헤더, 푸터 추가 했습니다.
#160

[Fix] 회원정보 수정 페이지(header, footer 추가)

---

src/hooks/useLike.ts
src/hooks/useMessage.ts
src/hooks/useNotificationList.ts
src/pages/MessagePage/Message.tsx
src/pages/NotificationPage/NotificationList.tsx
src/pages/PostViewPage/PostDetail/index.tsx
src/pages/ReflectionViewPage/ReflectionDetail/index.tsx

알림 보내는 기능을 추가하면서 전반적으로 수정이 들어갔습니다

[Fix] 알림 기능 수정

---

src/components/PostList/PostListItem.tsx
src/components/PostList/index.tsx
src/components/UserList/UserListItem.tsx
src/components/UserList/index.tsx
src/pages/SearchPage/OptionSelector.tsx
src/pages/SearchPage/SearchInput.tsx
src/pages/SearchPage/index.tsx

- 유저 검색 시 프로필 이미지 나타나도록 작업했습니다.
- 유저 클릭 시 해당 유저의 상세 정보로 이동하도록 작업했습니다.
- 게시글 클릭 시 해당 게시글로 이동하도록 작업했습니다.
- 검색 옵션 변경 시 기존에 검색 내역이 초기화 되도록 했습니다.
- 검색어를 입력한 경우에만 예외 처리 텍스트가 나타나도록 수정했습니다.
- `PostList, UserList` 내에서 처리해야 할 로직과 고정된 `Width` 값 삭제했습니다.
#86 
추후에 `form`의 경우 `react-hook-form`으로 변경하는 것이 좋을 것 같습니다 ! (현재는 코드에 맞춰 추가만 했습니다.)

[Fix] Search Page(검색) 페이지 추가 작업 진행

---

src/components/Footer/index.tsx
src/components/MainHeader/index.tsx
src/components/PageHeader/index.tsx
src/components/PageLayout/index.tsx
src/pages/MainPage/index.tsx
src/pages/MyPage/index.tsx
src/pages/PostViewPage/PostDetail/Content.tsx
src/pages/PostViewPage/PostDetail/Footer.tsx
src/pages/PostViewPage/PostDetail/Header.tsx
src/pages/PostViewPage/PostDetail/Settings.tsx
src/theme/index.ts

[Style] 각 스타일 수정하였습니다

---

src/components/OnlineUserProfile/index.tsx
src/pages/BoardPage/OnlineUsers.tsx

- 실시간 접속자 수 상세 정보 클릭 가능하도록 수정했습니다.

[Fix] 실시간 접속자 상세 정보 확인 기능

---

src/components/UserList/UserListItem.tsx
src/components/UserList/index.tsx
src/pages/MessagePage/index.tsx

- 메시지 배경색 다크모드 설정하였습니다
- 유저리스트의 유저닉네임 폰트 색상 상속받게 설정하였습니다

[Style] 메시지배경색 다크모드, 유저리스트 다크모드 색상 추가

---

src/pages/Login/LoginForm.tsx
src/pages/Login/LoginLogoTitle.tsx
src/pages/MainPage/GuestGrassBox.tsx
src/pages/MyPage/UpdateUserInfo/index.tsx
src/pages/PostEditPage/index.tsx
src/pages/SignUp/index.tsx

[Fix] Styles

---

src/pages/MainPage/DdayModal/index.tsx

MainDdayModal 텍스트 간격 수정 했습니다. (정말 간단한 수정 사항 입니다.)

[Styel ] MainDdayModal 텍스트 간격 수정

---

src/components/Comment/CommentForm.tsx
src/components/PostList/index.tsx
src/components/common/UserContentBlock/index.tsx
src/hooks/useMessage.ts
src/pages/MainPage/LoginProfile.tsx
src/pages/MessagePage/Message.tsx
src/pages/MessagePage/MessageForm.tsx
src/pages/PostViewPage/PostDetail/index.tsx

- 메시지, 포스트 등 전반적으로 에러 및 스타일 수정했습니다

[Fix] 전반적인 수정

---

src/pages/SearchPage/SearchInput.tsx
src/pages/SearchPage/index.tsx

- Search 검색어 1~30글자로 글자 수 제한했습니다.
- Search 검색어 처음부터 input에 focus 가도록 수정했습니다.
#86

[Fix] SearchPage 검색어 글자수 제한 및 autoFocus 추가

---

src/components/Comment/CommentForm.tsx
src/components/Comment/index.tsx
src/hooks/useComment.ts
src/pages/PostViewPage/PostDetail/index.tsx

🐛 댓글 작성 시 알림 보내기 기능 수정

---

src/components/Comment/CommentForm.tsx
src/components/Comment/index.tsx
src/components/common/UserContentBlock/index.tsx

- Comment 페이지 Style 수정했습니다. (배경색 추가 및 cursor 추가)

[Style] Comment Style 수정(cursor 추가, 배경색 추가)

---

src/components/MainHeader/index.tsx
src/components/PageHeader/index.tsx
src/components/common/MyModal/index.tsx
src/pages/PostViewPage/PostDetail/Settings.tsx
src/pages/PostViewPage/PostDetail/index.tsx
src/pages/ReflectionViewPage/ReflectionDetail/index.tsx
src/pages/TimerPage/TimerSettingModal/index.tsx
src/pages/TimerPage/index.tsx

- 메인 Dday 모달 Style 수정(다크 모드 시 색상 변경)
- 타이머 페이지 색상 변경(다크 모드 시 색상 변경)
- PostView 페이지 수정, 삭제 모달 기능 수정
- Reflection 페이지 수정, 삭제 모달 기능 추가
- Header Badge 임시 제거

[Style/Fix] 전체적인 스타일 수정 및 기능 개선

---

src/components/Comment/CommentForm.tsx
src/components/Comment/index.tsx
src/pages/MessagePage/MessageForm.tsx
src/pages/MyPage/UpdateUserInfo/index.tsx
src/pages/MyPage/index.tsx
src/pages/PostEditPage/index.tsx
src/pages/PostViewPage/ErrorFallback.tsx
src/pages/PostViewPage/index.tsx
src/pages/ReflectionViewPage/ReflectionDetail/TextCard.tsx
src/pages/ReflectionViewPage/index.tsx
src/pages/UserInfo/UserProfile.tsx
src/pages/UserInfo/UserProfileButton.tsx

ReflectionView 페이지 폰트 사이즈 수정했습니다. (타입 에러 나는 부분도 수정했습니다.)

[Style] ReflectionView 페이지 Style 수정(본문 폰트 크기 변경)

---

src/components/PageLayout/index.tsx
src/pages/Login/index.tsx

- 모바일 디바이스에서 100vh가 깨지는 현상 발생하여 수정하였습니다.
- PageLayout높이를 100vh => 100dvh로 단위 변경하였습니다
- PageLayout에 justify: center 줘서 수직 가운데정렬 맞추었습니다.
- LoginPage의 컨테이너를 Flex로 변경 후 마진, 상-하 패딩 삭제하였습니다.

[Fix] mobile device

---

src/pages/PostViewPage/PostDetail/Container.tsx
src/pages/ReflectionViewPage/ReflectionDetail/index.tsx

- PageLayout에 justify=center 넣은것 때문에 중앙정렬된 페이지들에 flex=1 부여하였습니다
- ReflectionViewPage의 UI구조를 아주 살짝 바꾸었습니다. PostViewPage와 동일하게 Commnets컴포넌트까지 Post컴포넌트가 감싸게 변경하엿습니다.

[Fix] post detail page
