- src/components/MainHeader/index.tsx
- src/components/common/TextIconButton/index.tsx
- src/components/common/UserList/index.tsx
- src/stories/components/Footer.stories.ts
- src/stories/components/MainHeader.stories.ts
- src/stories/components/UserList.stories.ts
- 검색 페이지와 잔디랭킹에서 사용할 UserList컴포넌트를 만들었습니다
- TextIconButton 컴포넌트의 배경색상을 하양=>투명으로 수정하였습니다
- MainHeader컴포넌트도 여타 Flex를 컨테이너로 사용하는 컴포넌트들처럼 타입을 FlexProps로 변경하였습니다
#7 5번째 태스크입니다
content글자와 아이콘의 간격을 닉네임과 이미지의 간격과 동일하게 수정하였습니다
> [Wip] 공통 컴포넌트 제작(5) UserList, (TextIconButton, MainHeader 수정사항 발생)

- src/apis/instance.ts
- interceptors.response 설정 삭제 및 localStorage
- interceptors에서 대신 오류처리를 해주지 않고 바로 에러를 반환하도록 설정
- #19 해당 PR에서 localStorage 및 로그인 시 토큰 저장 기능이 있어서, 이 PR이 merge된 이후에 정상적으로 토큰 사용이 가능할 것 같습니다.
> [Fix] axios interceptors 옵션 수정

- src/components/common/PostListItem/index.tsx
- src/components/common/TextIconButton/index.tsx
- src/components/common/UserListItem/index.tsx
- src/stories/components/PostListItem.stories.ts
- src/stories/components/TextIconButton.stories.ts
- src/stories/components/UserListItem.stories.ts
- 글 목록에서 사용할 PostListItem 컴포넌트를 제작하였습니다(스토리북 포함)
- TextIconButton의 text방향 지정 및 텍스트 스타일 지정 등 유연성을 더 늘렸습니다.
#7 6번째 태스크입니다
```jsx
const Component = ({flexStyle, textStyle, iconStyle, etcProps}) => {
<Flex {...flexStyle}>
<Text {...textStyle}>
<Icon {...IconStyle}>
...
}
```
컴포넌트 props의 덩치가 너무 커지는건 아닌가 고민됩니다ㅎㅎ
재사용 가능하게 만든다는 것이 참으로 어려운 것 같습니다! 이번에 TextIconButton도 꽤 수정사항이 생겨서 같이 봐주시면 감사하겠습니다.
> [Wip] 공통 컴포넌트 제작(6) PostListItem, TextIconButton(수정)

- src/pages/404Page/index.tsx
- src/pages/BoardEnterPage/index.tsx
- 404Page에서 `/boardd/free` 처럼 중첩 라우터일 때 404 이미지가 깨지는 버그 수정
- BoardEnterPage에서 `/board` 일 때 아무것도 출력되지 않는 버그 수정
#44 #61 
버그를 수정한 것이라 코드 변경 내용은 많지 않습니다 !
봐주실 코드의 양은 많지 않습니다 :)
> [Hotfix] 404Page, BoardEnterPage Error 수정

- .storybook/preview.ts
- src/components/PageHeader/index.tsx
- src/stories/components/PageHeader.stories.ts
페이지 헤더 뒤로가기 클릭시 뒤로가기 및 아이콘 누를시 라우팅 처리 완료하였습니다
#71 입니다
짧아서 거의 볼게 없습니다!
> [Fix] PageHeader컴포넌트 아이콘 클릭시 페이지 이동되게 변경 및 스토리북 수정(간단)

- src/components/Footer/index.tsx
- src/stories/components/Footer.stories.ts
- src/test/getInteractiveMap.test.ts
- src/utils/getInteractiveMap.ts
- 푸터 아이콘 path기반 하이라이트 및 클릭시 라우팅 이동
- 푸터 스토리북 수정
#73 입니다
- 배열을 만들어 TextIconButton을 map메서드로 뿌려주었습니다
- Map자료구조를 쌍방향으로 설정하여 영문=>한글, 한글=>영문에 대응하였습니다
> [Fix] 푸터 아이콘 하이라이트 및 라우팅 (살짝간단?)

- src/pages/MainPage/BoardListPreview.tsx
- MainPage에서 게시판 더보기 버튼 클릭 시 '/board' 로 넘어가게 처리 했습니다
나머지 처리해야 할 것은, DB 삭제 후 정식 데이터를 삽입한 후 작업이 가능할 것 같아 우선적으로 처리할 수 있는 부분을 완료했습니다.
봐주실 코드의 양은 적습니다 !
> [Feature] MainPage 게시판 더보기 버튼 클릭 시 '/board' 로 넘어가게 처리

- src/app/App.tsx
- src/components/Footer/index.tsx
- src/components/OnlineUserProfile/index.tsx
- src/components/PageHeader/index.tsx
- src/hooks/useChannelList.ts
- src/pages/BoardPage/BoardPostList.tsx
- src/pages/BoardPage/OnlineUsers.tsx
- src/pages/BoardPage/WriteButton.tsx
- src/pages/BoardPage/index.tsx
- BoardPage에서 게시글을 불러올 때 사용하던 `TEST_CHANNEL_ID` 를 제거하고, DB에 등록된 채널의 id를 사용하도록 수정했습니다.
- BoardPage에서 스타일을 수정했습니다.
많은 내용이 추가되진 않았지만 `BoardPage > index.tsx` 부분에서 
`<BoardPostList channelId={(pathInfo && pathInfo._id) || ''} />` 이 조금 거슬릴 것 같습니다.. `|| ' '`을 추가하지 않는다면 `pathInfo는 undefined일 수 있습니다.` 라는 에러가 뜨고, `BoardPostList` 안에 type 지정하는 곳에서 `string || undefined` 를 넣자니 애매해서 일단은 || 연산자를 사용하였습니다. 해결 방법에는 어떤 것이 있을까요 ?
봐주실 코드의 양은 많지 않습니다 !
> [Fix] BoardPage channel id 변경, 스타일링 수정

- src/hooks/useTodayTimePost.ts
#107 
- new Date()에 createAt값을 넣어 한국 시간으로 만들어 준 후, toLocaleString을 이용하여 `YYYY-MM-DD`형태로 만들어준 뒤 비교했습니다
짧습니다
> [Fix] useTodayTimerPost내부 날짜비교로직 수정 (간단)

- src/apis/channel.ts
- src/apis/type.ts
- src/hooks/useAuth.ts
- src/pages/Login/index.tsx
- src/pages/SignUp/index.tsx
- 회원 가입 시 fullName 필드에 { name: "이름" , channelId: "채널 ID"} 추가
- 회원가입 시 페이지 접속 시 관리자 계정 로그인
- 회원가입 페이지에서 다른 페이지로 이동 시 관리자 인증 토큰 제거
#100 
- 채널 생성 시 관리자 인증이 필요하여 임의로 회원가입 페이지 접근 시 관리자 로그인을 진행했습니다.
- 이후 해당 페이지에서 다른 페이지로 이동할 때 인증 토큰을 제거했습니다.
- 해당 페이지에서 회원가입 시 회원 로그인 후 이전 페이지로 이동시켰습니다.
- `useEffect` 사용을 많이 했는데, 이렇게 처리해도 괜찮을까요?? 좋은 방법이 있다면 제안 주시면 수정하도록 하겠습니다.
> [Fix] 회원가입 시(네임 필드에 채널 추가 했습니다.)

- src/hooks/useAuth.ts
- src/pages/MyPage/Account/index.tsx
- src/pages/MyPage/UpdateUserInfo/index.tsx
- src/types/user.ts
- Account 페이지에서 **나의 정보를 가지고 올 때 JSON화 되어 있는 fullName을 `JSON.parse`로 가지고 옵니다.**
- 데이터를 가지고 온 뒤 fullName **내부에 있는 `name, timerChannelId` 값을 `UpdateUserInfo` 페이지에 props로 전달**합니다.
- `UpdateUserInfo` 페이지에서 회원정보 수정할 때 **`fullName` 구조에 맞게 변경해서 `JSON.stringify`로 데이터를 전달**합니다. (fullName: {name, timerChannelId)
#102 
수정하기 전 회원가입한 유저들은 fullName 필드가 string이기 때문에 회원 데이터를 초기화하지 않고 merge 하면 에러가 발생할 수 있습니다.
> [Fix] UpdateUserInfo(회원정보 수정) 페이지 - fullName 구조 변경으로 인한 수정

- src/components/Grass/GrassCell.tsx
- src/components/Grass/index.tsx
- src/stories/components/Grass/GrassCell.stories.ts
- src/stories/components/Grass/index.stories.ts
- src/utils/calcGrassPercentage.test.ts
- src/utils/calcGrassPercentage.ts
- 잔디를 보여줄 Grass컴포넌트를 제작하였습니다
- 잔디 칸 하나를 이루는 GrassCell컴포넌트를 제작하였습니다(합성 컴포넌트로 해도 좋을거같네요)
- 기준 시간과 현재 시간을 받아서 색 농도 퍼센트를 계산해줄 calcGrassPercentage 유틸함수도 제작하였습니다
- 마우스 올려보면 tooltip에 회고없음 or 회고한 날짜가 나옵니다
#53  입니다
- 받아올때 데이터 구조를 아래처럼 받아오면 좋을거 같았는데, 어떻게 생각하시나요?
`{ time: '06:07:00', createdAt: '2024-01-01T20:48:19.816Z' }` 참고로 time은 회고한 시간입니다 ㅎㅎ
- 기록을 계산하는 로직이 적절한지 궁금합니다.
- 내부에서 new Date를 사용하는데  밖에서 date객체를 받아와서 처리하는건 어떤지 궁금합니다
- 색상도 사용자가 설정할 수 있게하면 좋을거같은데, 어떻게 생각하시나용?
> [Feature] Grass 컴포넌트 제작

- src/pages/MainPage/DdayModal/index.tsx
- src/pages/MainPage/LoginDday.tsx
- src/utils/calculateDday.test.ts
- src/utils/calculateDday.ts
- dday 계산로직을 0시0분0초로 변경하여 날짜가 이상하게 나오던 버그 수정하였습니다
- calculatedday 테스트 함수 제작하였습니다
- dday선택할 수 있는 최소 날짜(금일) 설정해두었습니다
#110  입니다
- `getTomorrow`함수로 최솟값을 넣어주고있는데, 불필요한 연산이 계속되는 것 같네요. 날짜가 바뀔때마다 해주면 좋을거같은데...useMemo를 사용하여 인자로 무슨 값을 넘겨주어야할까요
- `toLocaleString`이 메서드 정말 유용하네요 ㅎㅎ
> [Fix] Dday 컴포넌트 버그 수정 및 calculateDday테스트 함수 제작

- src/hooks/usePost.ts
- src/pages/ReflectionPostEditPage/index.tsx
- src/stories/pages/ReflectionPostEditPage/index.stories.tsx
- src/utils/getRecentEightDates.test.ts
- src/utils/getRecentEightDates.ts
- 회고 작성 페이지를 제작하였습니다
- usePost파일에 useEidtPost 훅 추가하였습니다
- usePostDetail에 enabled 인자 추가하였습니다. => 특정 값이 존재할때만 쿼리하는 기능입니다
- getRecentEightDates 함수 추가하였습니다. => 당일기준 -3일, +4일 날짜+요일 가져옵니다.
- querystring으로 `id`가 들어오면, usePostDetail을 이용하여 포스팅된 글자를 가져온 뒤, 각 input의 초기값으로 넣어줍니다.
- 또한 `id`가있으면 글쓰기 버튼 누를시 작성 대신 수정이 됩니다.
#117 
```js
maxLength={
validate.maxLength &&
//타입 추론 안되서 as키워드로 강제 변환
+(validate.maxLength as ValidationValueMessage).value
}
```
이부분 타입추론, 타입 narrowing이 잘 안되서 as키워드 사용하였는데 좋은 방법 있으면 알려주세용..ㅠㅠ
- 채널id와 채널 제목이 1대1 대응되는 자료구조가 있으면 좋을것 같습니다.
- 인증 관련 에러처리는 전역에서 에러바운더리로 잡기로 하였는데, 이곳에선 어떤 에러처리가 필요할까요?
- 인증이 되었는데도 에러가 발생했다면 서버문제니 다시 시도하기 정도면 좋을것 같긴 합니다
> [Feature] 회고 작성페이지 제작

- src/hooks/useChannels.ts
- src/hooks/usePost.ts
- src/pages/MainPage/BoardListPreview.tsx
- src/pages/MainPage/BoardListPreviewItem.tsx
- src/pages/MainPage/Dday.tsx
- src/pages/MainPage/MainBoardItem.tsx
- src/pages/MainPage/index.tsx
- 3개의 게시판을 불러왔습니다.
- 각 게시판의 첫 번째 포스트 제목을 출력 해줍니다.
- 게시판 영역을 클릭하면 해당 게시판 (BoardPage)로 이동합니다.
#85 
- `BoardListPreview > MainBoardItem` 로 가는 구조가 너무 복잡해 보일까요 ?
- 네이밍은 이해가 될 정도로 적절한가요 ?
MainPage에서 `Grass 컴포넌트 (props로 아무것도 안 넘겨줄 때 오류가 발생하여 코드에 추가하진 않았습니다.)` 를 추가하면 아래 사진과 같습니다.
> [Feature] MainPage 게시판 영역 기능 구현

- src/components/PostList/index.tsx
- src/utils/checkIsJson.test.ts
- src/utils/checkIsJson.ts
- caclulateTimeDiff이용하여 timeAgo(며칠전 등 나타내는 속성)실제 날짜와 비교하게 변경
- keyword 프롭스가 존재하지 않을 시 데이터를 그냥 내보내게 변경
- JSON.parse로 역직렬화 가능한 `post.title`은 역직렬화 하여 제목에 `JSON.parse(post.title).title`을 보여주게 변경
#119 
짧아서 크게 없습니다.
다만 역직렬화 가능한 타입인지 체크할때 try-catch를 이용해야하는게 참 신기하네요 ㅎㅎ
> [Fix] PostList 버그 수정

- src/components/MainHeader/index.tsx
- 메인헤더 상단 아이콘 네비게이팅되게 수정
- 아이콘+클릭이벤트 배열화 하여 map메서드로 뿌려주게 수정
- 아이콘 전부 material design아이콘으로 변경
#121 
간단합니다
> [Fix] 메인헤더 아이콘 관련 수정 (간단)

- src/pages/MyPage/MyPageListItem.tsx
- src/pages/MyPage/index.tsx
- src/pages/MyPage/myPageList.ts
- 프로필 이미지, 닉네임 영역을 클릭하면 내 정보 보기 페이지로 이동하도록 작업 했습니다.
- 메뉴 리스트에 내 정보 보기 리스트를 추가했습니다.
#132
마이페이지 리스트에 **내 정보 보기** 페이지를 추가했습니다. (추가로, 프로필 이미지, 닉네임 클릭 시에도 내 정보 보기 페이지로 이동 되도록 링크 추가했습니다.)
> [Fix] MyPage(마이페이지) 메뉴 리스트 추가

- src/app/App.tsx
- src/hooks/useTimer.ts
- src/main.tsx
- src/pages/TimerPage/index.tsx
- 타이머가 완료되어도 1초남는 버그 수정
- 쿼리 전역 설정 refetchOnWindowFocus: false,로 변경하였습니다
- reflectionPostEdit라우트 빠져있어서 추가하였습니다
#135 
전역에서 refetchOnWindowFocus: false 쿼리 옵션 주어서 윈도우 포커싱될때 쿼리 안하게 만들었습니다
> [Fix] 타이머 페이지 버그 수정 및 쿼리 전역 설정 변경 (간단)

- src/pages/SearchPage/OptionSelector.tsx
- src/pages/SearchPage/SearchInput.tsx
- src/pages/SearchPage/index.tsx
- 검색 시 요청이 여러 번 들어가는 것을 막았습니다.
- 옵션 or 검색어를 입력하지 않고 enter키를 눌렀을 때 alert 창으로 경고를 띄웁니다.
- FormControl을 사용하여 옵션 or 검색어를 입력하지 않았을 때 isInvalid를 사용하여 사용자에게 눈에 띄도록 처리해봤습니다.
#86 
- SearchPage에서는 채널 옵션을 불러오는 것을 제외하면 따로 query문을 사용하는 것이 없어 react-hook-form은 도입하지 않았습니다.
- 미처 확인 못한 경우가 있는지 알려주시면 바로 반영하겠습니다.
> [Fix] SearchPage 검색 시 요청이 여러번 들어가는 버그 수정

- src/components/common/UserContentBlock/index.tsx
- src/pages/MyPage/MyCommentList/MyCommentListItem.tsx
- src/pages/MyPage/MyCommentList/index.tsx
- MyCommentList 페이지에서 댓글을 클릭하면 댓글을 작성한 게시글로 이동합니다.
- 삭제 버튼을 누르면 삭제에 대한 이벤트 기능만 동작하도록 했습니다. (이벤트 전파 방지 코드 추가)
- UserContentBlock 컴포넌트 내부에 이벤트 추가했습니다. (전체 영역에 이벤트 걸 수 있는 코드 추가)
#158 
- 내가 작성한 댓글 페이지에서 댓글 클릭하면 댓글이 작성된 게시글로 이동시켰습니다.
- UserContentBlock 컴포넌트 이벤트 추가 및 서브 이벤트에 이벤트 전파 방지 코드 추가했습니다.
> [Fix] MyCommentList 페이지 기능 추가 및 UserContentBlock 컴포넌트 기능 개선

- src/constants/GrassDummy.ts
- src/pages/MainPage/GuestGrassBox.tsx
- src/pages/MainPage/LoginGrassBox.tsx
- src/pages/MainPage/index.tsx
- 로그인을 하고 바로 메인페이지로 갔을 때 잔디 내역이 안 뜨는 오류를 수정했습니다.
#147 
- myInfo의 유무에 따른 분기가 필요해서 `GuestGrassBox`, `LoginGrassBox` 컴포넌트를 분리하였습니다.
- 발견하지 못한 오류가 있다면 말씀 부탁드리겠습니다 !
> [Fix] MainPage Grass 컴포넌트 오류 해결 - 로그인 시 잔디 출력이 안되는 이슈

- src/pages/ReflectionPostEditPage/index.tsx
- 회고 인증 게시판의 channelId를 하드코딩해서 사용하던 부분을 초기화 이후 동적으로 id받아와서 사용하게 수정
- useChannelInfo훅을 사용하였습니다
> [Fix] 회고인증 게시판 글 보이게 수정
